name: Lint and Test
on: [push, workflow_dispatch]
jobs:
    build:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ["18.x", "16.x"]
                os: [ubuntu-latest]

        steps:
            - name: Disable Auto CRLF
              run: git config --global core.autocrlf false

            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install pnpm
              uses: pnpm/action-setup@v2.0.1
              id: pnpm-install
              with:
                  version: 7
                  run_install: false

            - name: Install deps
              run: pnpm install

            - name: Type check
              run: pnpm run tsc

            - name: Lint
              run: pnpm run eslint .
