name: Lint and Test
on: [push, workflow_dispatch]
jobs:
    build:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ["14.x", "16.x"]
                os: [ubuntu-latest]

        steps:
            - name: Disable Auto CRLF
              run: git config --global core.autocrlf false

            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: "npm"

            - name: Install global tools
              run: npm install -g eslint prettier typescript

            - name: Install deps
              run: pnpm install

            - name: Type check
              run: tsc --noEmit
